name: Check NS Disruptions

on:
  schedule:
    - cron: '*/5 * * * *'  # Elke uur uitvoeren

jobs:
  check-disruptions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install necessary tools
      run: sudo apt-get install -y jq

    - name: Call NS API and check for disruptions
      id: check_disruptions
      run: |
        RESPONSE=$(curl -s -H "Ocp-Apim-Subscription-Key: ${{ secrets.YOUR_SUBSCRIPTION_KEY }}" "https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions")
        DISRUPTION_COUNT=$(echo $RESPONSE | jq '[.[] | select(.type == "DISRUPTION")] | length')

        if [[ $DISRUPTION_COUNT -gt 0 ]]; then
          echo "Disruptions detected."
          echo "::set-output name=disruption::true"
        else
          echo "No disruptions detected."
          echo "::set-output name=disruption::false"
        fi

    - name: Send mail if disruptions are detected
      if: steps.check_disruptions.outputs.disruption == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yourmailserver.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: NS Disruption Detected
        # Change the body as per your requirement
        body: A disruption was detected in the NS service.
        to: your-email@example.com
        from: sender-email@example.com
